### ISSUE TITLE
templates dir missing

### ISSUE THREAD

**Issue by Almad** [mdirolf/DjanMon#1]
I don't know if DjanMon should run "out of the box", but I assume so.

If yes, template dir linked from settings.py is missing, resulting into TemplateDoesNotExist at /
status/index.html

on index page.,

**Comment by mdirolf** [comment]
oops - i forgot to add the templates and static directory to version control - just pushed them.

thanks for the heads up!

**Comment by Almad** [comment]
Works now, thanks :)
