### ISSUE TITLE
Cannot upload file

### ISSUE THREAD

**Issue by Almad** [mdirolf/DjanMon#2]
When uploading file (and adding text to message), I get

NameError at /
global name 'web' is not definedRequest Method: POST
Request URL:    http://localhost:8000/
Exception Type: NameError
Exception Value:    global name 'web' is not defined
Exception Location: /home/almad/download/DjanMon/status/views.py in index, line 52
Python Executable:  /usr/bin/python
Python Version: 2.6.2

**Comment by mdirolf** [comment]
ah you found a code path i forgot to test - should be fixed now. just a heads up that you should only run into that when trying to upload a file with an unsupported extension - the only files that will upload successfully are images - and we just check the file extension for popular image extensions.
